-- --------------------------------------------------------
-- Host:                         192.168.56.19
-- Server version:               10.1.37-MariaDB - Source distribution
-- Server OS:                    Linux
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table anime_db.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table anime_db.migrations: ~2 rows (approximately)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2022_12_05_012330_create_titles_table', 1),
	(2, '2022_12_05_144344_create_notes_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- Dumping structure for table anime_db.notes
CREATE TABLE IF NOT EXISTS `notes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `titles_id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `notes_titles_id_foreign` (`titles_id`),
  CONSTRAINT `notes_titles_id_foreign` FOREIGN KEY (`titles_id`) REFERENCES `titles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table anime_db.notes: ~3 rows (approximately)
/*!40000 ALTER TABLE `notes` DISABLE KEYS */;
INSERT INTO `notes` (`id`, `title`, `notes`, `titles_id`, `created_at`, `updated_at`) VALUES
	(1, 'Review Chainsaw Man Eps 2a edit', 'aa', 1, '2022-12-07 03:52:31', '2022-12-07 06:55:12'),
	(2, 'Review Eps 3', 'Anime ini bagus, sekian dan terima kasih', 2, '2022-12-07 04:11:01', '2022-12-07 04:11:01');
/*!40000 ALTER TABLE `notes` ENABLE KEYS */;

-- Dumping structure for table anime_db.titles
CREATE TABLE IF NOT EXISTS `titles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rating` double NOT NULL,
  `studio` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `season` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `year` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `genre` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `desc` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table anime_db.titles: ~36 rows (approximately)
/*!40000 ALTER TABLE `titles` DISABLE KEYS */;
INSERT INTO `titles` (`id`, `title`, `rating`, `studio`, `season`, `year`, `genre`, `desc`, `image`, `created_at`, `updated_at`) VALUES
	(1, 'Chainsaw Man', 8.83, 'MAPPA', 'Fall', '2022', 'Action, Fantasy', 'Denji dirampok dari kehidupan remajanya yang normal, tidak memiliki apa-apa selain hutang ayahnya yang sangat besar. Teman satu-satunya adalah hewan peliharaannya, Pochita, iblis gergaji mesin, yang dengannya dia membunuh iblis demi uang yang pasti berakhir di saku yakuza. Yang bisa dilakukan Denji hanyalah memimpikan kehidupan yang baik dan sederhana: hidup dengan makanan enak dan pacar cantik di sisinya. Tapi tindakan pengkhianatan rakus oleh yakuza menyebabkan kematian Denji yang brutal dan terlalu cepat, menghancurkan semua harapan dia untuk mencapai kebahagiaan.\r\n\r\nHebatnya, kontrak lama memungkinkan Pochita untuk bergabung dengan almarhum Denji dan memberikan kekuatan iblis padanya, mengubahnya menjadi hibrida yang mampu mengubah bagian tubuhnya menjadi gergaji mesin. Karena kemampuan baru Denji menimbulkan risiko yang signifikan bagi masyarakat, pemburu setan elit Biro Keamanan Publik, Makima, membawanya masuk, membiarkannya hidup selama dia mematuhi perintahnya. Dipandu oleh janji kehidupan konten bersama seorang wanita yang menarik, Denji mencurahkan segalanya dan bertarung dengan sekuat tenaga untuk mewujudkan mimpinya yang naif.', 'https://cdn.myanimelist.net/images/anime/1806/126216.webp', NULL, NULL),
	(2, 'Spy x Family Part 2', 8.57, 'Cloverworks, Wit Studio', 'Fall', '2022', 'Action, Comedy', 'Dengan keberhasilan Anya Forger terdaftar di Eden Academy yang terkenal, Operasi Strix maju ke tahap kedua. Untuk menyelidiki politikus Ostanian Donovan Desmond, Anya harus berteman dengan putranya Damian atau mengumpulkan delapan Stella Stars untuk menjadi Imperial Scholar. Untungnya, Anya sudah mendapatkan bintang pertamanya. Dalam perayaan, ayah angkatnya, Loid, memutuskan untuk memenuhi keinginannya untuk mengadopsi seekor anjing.\r\n\r\nSelama pencarian anjing mereka, Loid menerima perintah baru dari atasannya, yang menemukan bahwa sekelompok mahasiswa Universitas Berlint berencana untuk membunuh Menteri Brantz Westalis menggunakan bom yang dikenakan oleh anjing terlatih. Saat Loid mencoba menghentikan rencana mereka, Anya menemukan markas operasi teroris. Di sana, dia berteman dengan seekor anjing peramal yang baik hati yang kemudian diberi nama Bond oleh keluarganya.\r\n\r\nMeskipun Forgers terus menjalani kehidupan individu mereka secara rahasia, keluarga tersebut — dengan tambahan baru yang lembut — tetap bersatu melalui semua rintangan tidak biasa yang menghadang mereka.', 'https://cdn.myanimelist.net/images/anime/1111/127508.webp', NULL, NULL),
	(3, 'Bleach', 9.1, 'Pierrot', 'Fall', '2022', 'Action, Adventure, Fantasy', 'Pengganti Soul Reaper Ichigo Kurosaki menghabiskan hari-harinya melawan Hollow, roh jahat berbahaya yang mengancam Kota Karakura. Ichigo melakukan pencariannya dengan sekutu terdekatnya: Orihime Inoue, teman masa kecilnya dengan bakat penyembuhan; Yasutora Sado, teman sekelas SMA-nya dengan kekuatan manusia super; dan Uryuu Ishida, saingan Quincy Ichigo.\r\n\r\nRutinitas main hakim sendiri Ichigo terganggu oleh kemunculan tiba-tiba Asguiaro Ebern, Arrancar berbahaya yang mengumumkan kembalinya Yhwach, raja Quincy kuno. Yhwach berusaha menyalakan kembali perseteruan darah bersejarah antara Soul Reaper dan Quincy, dan dia mengarahkan pandangannya untuk menghapus dunia manusia dan Soul Society untuk selamanya.\r\n\r\nYhwach meluncurkan invasi dua cabang ke Soul Society dan Hueco Mundo, rumah Hollow dan Arrancar. Sebagai pembalasan, Ichigo dan teman-temannya harus bertarung bersama sekutu lama dan musuh untuk mengakhiri kampanye pembantaian Yhwach sebelum dunia itu sendiri berakhir.', 'https://cdn.myanimelist.net/images/anime/1764/126627.webp', NULL, NULL),
	(4, 'Mob Psycho 100 III', 8.65, 'Bones', 'Fall', '2022', 'Action, Comedy, Supranatural', 'Setelah menggagalkan plot yang mengancam dunia, Shigeo "Mob" Kageyama kembali untuk menangani aspek kehidupan duniawinya yang lebih melelahkan—dimulai dengan mengisi formulir karier sekolahnya yang menegangkan. Sementara itu, dia terus membantu mentornya Arataka Reigen dan rekrutan baru kantor tersebut, Katsuya Serizawa, dalam menyelesaikan kasus paranormal klien mereka. Sambil melanjutkan tugasnya, Mob juga berupaya untuk mendapatkan lebih banyak kemandirian dalam kehidupan esper dan manusianya, serta berusaha untuk berintegrasi lebih baik dengan orang-orang di sekitarnya.\r\n\r\nNamun, tantangan supranatural dan biasa baru menguji kestabilan emosi Mob dan memaksanya untuk menghadapi kenyataan di sekitarnya. Saat dia berusaha untuk terus maju di jalan menuju kedewasaan, Mob harus menyelesaikan krisis emosionalnya dan menilai kembali kenaifan yang telah dia pertahankan begitu lama.', 'https://cdn.myanimelist.net/images/anime/1228/125011.jpg', NULL, NULL),
	(5, 'Bocchi the Rock!', 8.75, 'Cloverworks', 'Fall', '2022', 'Comedy', 'Kerinduan untuk berteman dan tampil live dengan sebuah band, Hitori "Bocchi" Gotou yang kesepian dan cemas secara sosial mencurahkan waktunya untuk bermain gitar. Pada hari yang menentukan, Bocchi bertemu dengan drummer lama Nijika Ijichi, yang mengundangnya untuk bergabung dengan Kessoku Band saat gitaris mereka, Ikuyo Kita, melarikan diri sebelum pertunjukan pertama mereka. Segera setelah itu, Bocchi bertemu dengan rekan band terakhirnya—bassis keren Ryou Yamada.\r\n\r\nMeskipun penampilan pertama mereka bersama di bawah standar, gadis-gadis itu merasa diberdayakan oleh kecintaan mereka yang sama terhadap musik, dan kita segera bergabung kembali dengan Kita. Menemukan kebahagiaan dalam tampil, Bocchi dan rekan bandnya berusaha keras untuk berkembang sebagai musisi sambil memanfaatkan hari-hari sekolah menengah mereka yang singkat.', 'https://cdn.myanimelist.net/images/anime/1448/127956.jpg', NULL, NULL),
	(6, 'Fumetsu no Anata e 2nd Season', 8.05, 'Drive', 'Fall', '2022', 'Adventure, Drama, Supranatural', 'Setelah melihat cukup banyak kematian dan tragedi, Fushi yang abadi mengasingkan diri di sebuah pulau, membela diri dari musuh Nokkers. Namun, alih-alih menyerang Fushi secara terpisah, Nokkers mulai menargetkan permukiman di luar jangkauannya dengan harapan bisa memancingnya keluar. Segera, sebuah kelompok yang dikenal sebagai Penjaga — dipimpin oleh Hisame, keturunan dari prajurit almarhum Hayase — menemukan Fushi.\r\n\r\nTerinspirasi oleh bagaimana Fushi melindungi Pulau Janada dari Nokkers bertahun-tahun yang lalu, para Penjaga telah mendapatkan banyak pengikut dan diakui di seluruh dunia. Awalnya enggan, Fushi mengizinkan Penjaga untuk menemaninya ke lokasi serangan Nokkers baru-baru ini. Di desa mereka, Fushi bertemu dengan beberapa sekutu berharga, baik yang baru maupun yang lama. Tetapi karena konflik dengan Nokkers hanya menyebabkan lebih banyak kerugian, Fushi harus menemukan kekuatan batin untuk menghadapi kesedihannya yang tak terelakkan.', 'https://cdn.myanimelist.net/images/anime/1271/127700.jpg', NULL, NULL),
	(7, 'Blue Lock', 8.34, '8bit', 'Fall', '2022', 'Sports', 'Yoichi Isagi hanya beberapa saat lagi dari mencetak gol yang akan mengirim tim sepak bola sekolah menengahnya ke tingkat nasional, tetapi keputusan sepersekian detik untuk mengoper bola ke rekan setimnya membuatnya kehilangan kenyataan itu. Pahit, bingung, dan kecewa, Isagi bertanya-tanya apakah hasilnya akan berbeda seandainya dia tidak lolos. Saat striker muda itu pulang, undangan dari Japan Football Union menantinya. Melalui proses pengambilan keputusan yang sewenang-wenang dan bias, Isagi adalah satu dari tiga ratus striker U-18 yang dipilih untuk proyek kontroversial bernama Blue Lock.\r\n\r\nTujuan utama proyek ini adalah mengubah salah satu pemain terpilih menjadi striker bintang tim nasional Jepang. Untuk menemukan peserta terbaik, setiap berlian harus bersaing dengan yang lain melalui serangkaian kompetisi solo dan tim untuk naik ke puncak. Mengesampingkan keberatan etisnya terhadap proyek tersebut, Isagi merasa terdorong untuk berjuang menuju puncak, bahkan jika itu berarti menghancurkan impian 299 striker muda yang bercita-cita tinggi.', 'https://cdn.myanimelist.net/images/anime/1258/126929.webp', NULL, NULL),
	(8, 'Boku no Hero Academia 6th Season', 8.28, 'Bones', 'Fall', '2022', 'Action', 'Dengan Tomura Shigaraki di pucuk pimpinannya, mantan Tentara Pembebasan sekarang dikenal sebagai Front Pembebasan Paranormal. Kelompok kriminal terorganisir ini menimbulkan ancaman besar bagi Asosiasi Pahlawan, tidak hanya karena ukuran dan kekuatannya yang besar, tetapi juga kebiasaan Jin "Twice" Bubaigawara dan Gigantomachia yang sangat kuat.\r\n\r\nSaat intel baru dari pahlawan rahasia Keigo "Hawks" Takami mengonfirmasi bahwa Shigaraki tidak terlihat, Asosiasi Pahlawan memutuskan untuk menyerang markas musuh dengan serangan mendadak menggunakan seluruh asetnya—dan para siswa UA menemukan diri mereka di medan perang sekali lagi. Saat pertarungan berkecamuk, penjahat yang tidak curiga harus berkumpul kembali dan mundur, tetapi para pahlawan pemberani bertekad untuk membasmi mereka semua.', 'https://cdn.myanimelist.net/images/anime/1483/126005.webp', NULL, NULL),
	(9, 'Golden Kamuy 4th Season', 8.31, 'Brain\'s Base', 'Fall', '2022', 'Action, Adventure', 'Pada awal 1900-an Hokkaido setelah perang Rusia-Jepang, Saichi Sugimoto tanpa lelah mendulang emas. Dijuluki "Sugimoto the Immortal" karena tindakannya yang menantang maut dalam pertempuran, mantan prajurit itu mencari peruntungan untuk memenuhi janji yang dibuat kepada sahabatnya sebelum dia terbunuh dalam aksi: untuk menghidupi keluarganya, terutama jandanya yang membutuhkan perawatan. luar negeri karena penglihatannya yang memburuk. Suatu hari, seorang teman yang mabuk menceritakan kepada Sugimoto kisah tentang seorang pria yang membunuh sekelompok Ainu dan mencuri banyak uang emas. Sebelum ditangkap oleh polisi, dia menyembunyikan emas tersebut di suatu tempat di Hokkaido. Satu-satunya petunjuk ke lokasinya adalah peta berkode yang dia tato di tubuh teman satu selnya dengan imbalan bagian dari harta karun itu, jika mereka berhasil melarikan diri dan menemukannya.\r\n\r\nSugimoto tidak terlalu memikirkan kisah tersebut sampai dia menemukan mayat pria pemabuk itu memiliki tato yang sama dengan yang dijelaskan dalam cerita. Tapi sebelum dia bisa menenangkan pikirannya, seekor beruang grizzly — penyebab kematian pria itu — mendekati Sugimoto, berniat menghabiskan makanannya. Dia diselamatkan oleh seorang gadis Ainu muda bernama Asirpa, yang kebetulan ayahnya adalah salah satu Ainu yang terbunuh. Dengan keterampilan berburu Asirpa dan naluri bertahan hidup Sugimoto, pasangan itu setuju untuk bergabung dan menemukan harta karun — satu untuk mendapatkan kembali apa yang menjadi hak rakyatnya, dan yang lainnya untuk memenuhi keinginan temannya yang sekarat.', 'https://cdn.myanimelist.net/images/anime/1855/128059.webp', NULL, NULL),
	(10, 'Made in Abyss: Retsujitsu no Ougonkyou', 8.7, 'Kinema Citrus', 'Summer', '2022', 'Adventure, Drama, Fantasy, Mystery, Sci-Fi', 'Setelah selamat dari tantangan brutal Idofront, Riko sekarang memiliki White Whistle, memungkinkannya untuk turun ke lapisan keenam Abyss—The Capital of the Unreturned. Bersama Reg dan Nanachi, Riko mulai menjelajahi domain yang belum dipetakan, tempat reruntuhan Kota Emas yang dijanjikan berada.\r\n\r\nSaat ketiganya mulai beradaptasi dengan lingkungan yang keras, mereka segera menghadapi makhluk berbahaya dan pemandangan berbahaya. Ekspedisi mereka membawa mereka ke sebuah desa yang dihuni oleh makhluk aneh yang dikenal sebagai "lubang". Terlepas dari rasa tidak nyaman yang menyambut mereka, ketiganya berusaha untuk mengungkap misteri pemukiman dan warisan yang telah lama hilang dari para petualang yang terlupakan yang pernah turun ke dalam kengerian Abyss yang belum dijelajahi.', 'https://cdn.myanimelist.net/images/anime/1864/122519.webp', NULL, NULL),
	(11, 'Lycoris Recoil', 8.25, 'A-1 Pictures', 'Summer', '2022', 'Action', 'Jumlah aksi teroris di Jepang tidak pernah berkurang, berkat upaya sindikat yang disebut Direct Attack (DA). Organisasi tersebut mengangkat gadis yatim piatu sebagai pembunuh untuk melakukan pembunuhan di bawah program "Lycoris" mereka. Takina Inoue adalah Lycoris yang luar biasa dengan tujuan yang kuat dan kegemaran akan kesempurnaan. Sayangnya, situasi penyanderaan menguji kesabarannya, dan tindakan pembangkangan yang diakibatkannya menyebabkan dia dipindahkan dari DA. Tidak senang kehilangan satu-satunya tempat miliknya, dia dengan enggan tiba di markas operasi barunya—LycoReco, sebuah kafe yang menyamar.\r\n\r\nNamun, pasangan baru Takina ternyata sangat berbeda dari yang dia bayangkan. Meskipun menjadi keajaiban Lycoris yang terkenal, Chisato Nishikigi tampaknya hampir tidak peduli dengan tugasnya. Dia menyeret Takina dalam semua jenis pekerjaan serabutan dengan penjelasan sederhana untuk membantu orang yang membutuhkan. Takina semakin bingung saat Chisato menjatuhkan sekelompok penyerang bersenjata tanpa membunuh satu pun dari mereka. Merasa seperti ikan yang keluar dari air, Takina sangat ingin diterima kembali di DA—tetapi Chisato bertekad untuk membuktikan kepadanya bahwa hidup ini lebih dari sekadar mengambil mereka.', 'https://cdn.myanimelist.net/images/anime/1392/124401.webp', NULL, NULL),
	(12, 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 2n', 8.16, 'Lerche', 'Summer', '2022', 'Drama, Suspense', 'Kehidupan kembali di kapal pesiar setelah Ujian Khusus Pulau sama sekali bukan pelayaran yang mulus. Hampir segera setelah mereka kembali, siswa tahun pertama dari Tokyo Metropolitan Advanced Nurturing High School kembali menghadapi ujian khusus, dengan mempertaruhkan poin kelas dan individu.\r\n\r\nSelain aturan yang rumit, lebih banyak masalah muncul dalam bentuk Kakeru Ryuuen dan Kei Karuizawa. Marah dengan hasil tes sebelumnya, Ryuuen sangat ingin mengalahkan setiap kelas dalam tantangan baru menggunakan segala cara yang diperlukan. Sementara itu, Karuizawa, pilar penting Kelas D, hampir runtuh di bawah tekanan masa lalunya.\r\n\r\nPanggung sekarang diatur untuk Kiyotaka Ayanokouji untuk sekali lagi — menggunakan sepenuhnya perencanaan, pandangan ke depan, dan manipulasinya yang kejam — mengarahkan Kelas D menuju kemenangan saat pasukan musuh yang sangat dekat mencoba menjatuhkannya.', 'https://cdn.myanimelist.net/images/anime/1010/124180.webp', NULL, NULL),
	(13, 'Overlord IV', 8.11, 'Madhouse', 'Summer', '2022', 'Action, Adventure, Fantasy', 'E-Rantel, the capital city of the newly established Sorcerer Kingdom, suffers from a dire shortage of goods. Once a prosperous city known for its trade, it now faces a crisis due to its caution—or even fear—of its king, Ainz Ooal Gown. To make amends, Ainz sends Albedo to the city as a diplomatic envoy.\r\n\r\nMeanwhile, the cardinals of the Slane Theocracy discuss how to retaliate against Ainz after his attack crippled the Re-Estize Kingdom\'s army, plotting for the Baharuth Empire to take over the Sorcerer Kingdom. However, when Emperor Jircniv Rune Farlord El Nix arranges a meeting with the Theocracy\'s messengers at a colosseum, he is confronted by none other than Ainz himself.\r\n\r\nWith their secret gathering now out in the open, the emperor and his guests learn that Ainz has challenged the Warrior King, the empire\'s greatest fighter, to a duel. With Ainz\'s motivations beyond his comprehension, Jircniv can do nothing but watch as humanity\'s future changes before his very eyes.', 'https://cdn.myanimelist.net/images/anime/1530/120110.webp', NULL, NULL),
	(14, 'Yofukashi no Uta', 8.07, 'LIDENFILMS', 'Summer', '2022', 'Romance, Supranaturl', 'Kou Yamori adalah siswa sekolah menengah biasa yang berjuang untuk memahami konsep cinta yang rumit. Karena dia melihat sedikit akal untuk menyerah pada norma, dia segera berhenti sekolah. Diganggu dengan insomnia karena kemalasannya, Kou mulai berkeliaran di jalanan yang sepi di malam hari.\r\n\r\nSuatu malam, Kou bertemu dengan seorang gadis aneh bernama Nazuna Nanakusa yang percaya bahwa orang tetap terjaga di malam hari karena mereka tidak puas dengan bagaimana mereka menghabiskan hari mereka dan tidak dapat beristirahat sampai mereka melepaskan hambatan mereka. Nazuna menawarkan untuk membantu Kou dengan masalah tidurnya dan mengundangnya ke tempatnya, di mana dia meyakinkannya untuk berbagi futon dengannya. Merasa tidak nyaman, Kou hanya berpura-pura tertidur — saat itulah Nazuna tiba-tiba menggigit lehernya, mengungkapkan dirinya sebagai vampir!\r\n\r\nSementara Kou mengira gigitan itu akan mengubahnya menjadi vampir, spesifikasi transformasinya tidak sesederhana itu. Untuk berubah, dia harus digigit oleh seseorang yang sangat dia cintai. Siap untuk melepaskan kehidupan fana yang suram, Kou memutuskan tujuan baru: dia akan jatuh cinta dengan Nazuna dan menjadi vampir sendiri.', 'https://cdn.myanimelist.net/images/anime/1045/123711.webp', NULL, NULL),
	(15, 'Shadows House 2nd Season', 8, 'Cloverworks', 'Summer', '2022', 'Fantasy, Mystery', 'Setelah resolusi debut, Kate dan Doll Emilico resmi menjadi penghuni Rumah Bayangan. Namun, mereka terus-menerus diawasi oleh para Pembawa Bintang—sebuah kelompok elit yang bertanggung jawab atas sayap anak-anak. Untuk melarikan diri dari pengawasan mereka dan metode mengerikan yang mereka gunakan untuk menjaga kesetiaan semua orang, Kate dan Emilico harus berhati-hati terhadap siapa yang harus dipercaya dan bertujuan untuk menjadi Pembawa Bintang itu sendiri.\r\n\r\nSementara itu, para Pembawa Bintang menghadapi masalah mereka sendiri. Sosok berjubah misterius yang dijuluki "Tuan Jubah" telah masuk tanpa izin dan berkeliaran di sekitar sayap anak-anak. Pada awalnya, Master Robe dianggap tidak berbahaya, tetapi lebih banyak insiden mulai terjadi yang membahayakan nyawa Boneka — semuanya mengarah ke individu yang mencurigakan.\r\n\r\nUntuk meningkatkan reputasinya, Kate memutuskan untuk memecahkan misteri itu sendiri. Namun, dengan begitu sedikit petunjuk dan begitu banyak tersangka, pencarian Master Robe dan motif mereka menyerang mansion terbukti lebih menantang daripada yang dia bayangkan.', 'https://cdn.myanimelist.net/images/anime/1634/124231.webp', NULL, NULL),
	(16, 'Isekai Ojisan', 7.85, 'AtelierPontdarc', 'Summer', '2022', 'Comedy, Fantasy', 'Setelah pertemuan fatal dengan truk, paman Takafumi Takaoka, Yousuke "Ojisan" Shibazaki, koma selama 17 tahun. Ketika dia akhirnya sadar kembali, Ojisan mulai mengoceh dalam bahasa asing dan mengungkapkan bahwa dia telah dipindahkan ke dunia magis bernama Gran Bahamal. Takafumi menolak klaim pamannya sebagai omong kosong sampai mantra membuat secangkir air melayang di udara. Dalam kilasan kecemerlangan, pasangan ini membuat saluran YouTube untuk memamerkan kemampuan magis Ojisan.Tanggung jawab sekarang berada di pundak Takafumi untuk memperkenalkan Ojisan dengan semua yang telah terjadi selama ketidakhadirannya, termasuk mempercepatnya dengan internet, teknologi baru, dan yang mengejutkan, hasil dari perang konsol tahun 90-an — hasil yang terutama menyedihkan bagi penggemar berat SEGA. Dengan kebijaksanaan Ojisan dari pengalaman dunianya yang lain, mereka mengembangkan saluran YouTube dan menangani komentar dan troll online. Perjalanan duo paman-keponakan ini menjanjikan sesuatu yang tidak konvensional.', 'https://cdn.myanimelist.net/images/anime/1743/125204.webp', NULL, NULL),
	(17, 'Kumichou Musume to Sewagakari', 7.79, 'feel. , Gaina', 'Summer', '2022', 'Slice of Life', 'Kemasyhuran Tooru Kirishima tersebar jauh dan luas di dunia bawah. Dia paling dikenal sebagai "The Demon of Sakuragi" —seorang pria yang tidak takut melakukan kekerasan jika dianggap perlu. Setelah hampir membahayakan perjanjian damai, bosnya menugaskannya dengan pekerjaan tersulit yang pernah dia miliki: merawat Yaeka Sakuragi yang berusia tujuh tahun — putri kesayangan bos — sehingga Tooru mengerti apa artinya bertanggung jawab atas orang lain. kehidupan.\r\n\r\nPada awalnya, keduanya tampaknya tidak saling berhadapan, karena Tooru tidak tahu bagaimana berkomunikasi dengan Yaeka, dan gadis muda itu tidak terbiasa mengekspresikan emosinya. Namun, seiring berjalannya waktu, mereka menjadi saling memahami meskipun ada perbedaan. Tangan kanan bos yakuza yang menakutkan dan anak yang harus dia lindungi akan mengetahui bahwa keluarga tidak selalu terikat oleh darah.', 'https://cdn.myanimelist.net/images/anime/1454/122063.webp', NULL, NULL),
	(18, 'Love Live! Superstar!! 2nd Season', 7.77, 'Sunrise', 'Summer', '2022', 'Slice of Life', 'Saat satu tahun lagi dimulai di Sekolah Menengah Wanita Yuigaoka, mengantar sekelompok siswa baru, klub idola sekolah Liella! bersemangat untuk memperluas keanggotaan mereka. Namun, Liella! sangat populer karena bakat luar biasa yang terus mereka tampilkan; dengan demikian, siswa baru kurang berani bahkan untuk mempertimbangkan mendekati klub, karena takut akan pelatihan keras yang mungkin ada di depan.Di tengah kekhawatirannya, pemimpin klub dan salah satu pendiri Kanon Shibuya bertemu dengan siswa tahun pertama Kinako Sakurakouji dan bercerita tentang dunia idola sekolah. Hal ini membuat Kinako terkagum-kagum, tetapi karena dirinya sendiri biasa-biasa saja, dia merasa dia tidak akan mampu menandingi penampilan penuh semangat dari Liella yang brilian! anggota. Meskipun demikian, Kinako menerima dorongan untuk bergabung dengan grup dan datang untuk berbagi impian mereka meraih bintang sekali lagi di acara Love Live! Kompetisi.', 'https://cdn.myanimelist.net/images/anime/1238/124173.webp', NULL, NULL),
	(19, 'Kaguya-sama wa Kokurasetai: Ultra Romantic', 9.09, 'A-1 Pictures', 'Spring', '2022', 'Comedy, Romance', 'Anggota elit dewan siswa Akademi Shuchiin melanjutkan kejenakaan mereka sehari-hari. Presiden dewan Miyuki Shirogane bentrok setiap hari melawan wakil presiden Kaguya Shinomiya, masing-masing berjuang mati-matian untuk mengelabui yang lain agar mengakui cinta romantis mereka. Kaguya berjuang dalam batas-batas ketat keluarganya yang kaya dan tegang, memberontak terhadap sikapnya yang dingin saat dia bersikap ramah pada Shirogane dan teman-temannya yang lain.Sementara itu, bendahara dewan Yuu Ishigami menderita di bawah beban cintanya yang putus asa pada Tsubame Koyasu, seorang kakak kelas populer yang membantu menanamkan kepercayaan baru padanya. Miko Iino, anggota OSIS terbaru, semakin dekat dengan Ishigami pelanggar aturan sambil berjuang untuk mengatasi kode moral otoriternya sendiri.Saat cinta semakin berkembang di Akademi Shuchiin, petugas OSIS menyeret teman luar mereka ke dalam konflik komedi yang semakin meningkat.', 'https://cdn.myanimelist.net/images/anime/1160/122627.webp', NULL, NULL),
	(20, 'Kingdom 4th Season', 8.77, 'Pierrot, Studio Signpost', 'Spring', '2022', 'Action', 'Menyusul kesimpulan dari kampanye koalisi skala besar, keseluruhan China berada dalam kondisi pemulihan ekonomi. Pemenang pertempuran, negara bagian Qin, tidak berbeda. Di sana, partai politik pimpinan Ying Zheng dan Buwei Lü melanjutkan konflik batin mereka. Setelah memainkan peran sebagai raja dalam pertempuran koalisi, Zheng mendapat kepercayaan dari rakyat—tetapi Lü masih jauh dari pertarungan. Dalam 18 bulan, dia berencana menghentikan upacara kedewasaan Zheng.Sementara itu, pasukan Zhao yang berjumlah 20.000 pasukan telah berangkat menuju Qin. Di istana kerajaan, karena kurangnya jenderal yang mampu menanggapi ancaman yang masuk, Lü dengan licik menyarankan agar Zheng mengambil alih komando. Namun, Cheng Jiao, saudara tiri Zheng, malah menjadi sukarelawan. Saat mereka semakin percaya satu sama lain selama pertempuran koalisi, Zheng sekarang menerima Jiao sebagai penggantinya.Namun, pasukan Zhao mundur hanya setengah hari setelah bentrok dengan pasukan Jiao. Dengan masalah yang muncul dengan cepat dalam bayang-bayang, perjuangan internal Qin semakin rumit. Hanya ada dua pria yang menurut Zheng bisa dia andalkan: Bi, seorang jenderal yang memimpin 30.000 orang; dan Xin, pemimpin pasukan Fei Xin.', 'https://cdn.myanimelist.net/images/anime/1566/122794.webp', NULL, NULL),
	(21, 'Spy x Family', 8.72, 'Cloverworks, Wit Studio', 'Spring', '2022', 'Action, Comedy', 'Politisi korup, nasionalis yang hiruk pikuk, dan kekuatan penghasut perang lainnya terus-menerus membahayakan lapisan tipis perdamaian antara negara tetangga Ostania dan Westalis. Terlepas dari plot mereka, mata-mata terkenal dan ahli penyamaran "Twilight" memenuhi misi berbahaya satu demi satu dengan harapan tidak ada anak yang harus mengalami kengerian perang.Di kota Berlint yang ramai di Ostania, Twilight memakai nama samaran "Loid Forger", seorang psikiater ternama. Namun, niat sebenarnya adalah untuk mengumpulkan informasi tentang politisi terkemuka Donovan Desmond, yang jarang muncul di depan umum di sekolah putranya: Akademi Eden yang bergengsi. Meminta bantuan pegawai balai kota yang belum menikah Yor Briar untuk bertindak sebagai istrinya dan mengadopsi Anya yatim piatu berusia enam tahun yang penasaran sebagai putrinya, Loid menjalankan rencana induknya. Dia akan mendaftarkan Anya di Akademi Eden, di mana Loid berharap dia akan unggul dan memberinya kesempatan untuk bertemu Donovan tanpa menimbulkan kecurigaan.Sayangnya bagi Loid, pria dengan bakatnya pun kesulitan memerankan sosok ayah dan suami yang penyayang. Dan seperti halnya Loid yang menyembunyikan identitas aslinya, Yor—yang merupakan pembunuh bawah tanah yang dikenal sebagai "Thorn Princess"—dan Anya—seorang esper yang bisa membaca pikiran orang—juga tidak punya rencana untuk mengungkapkan rahasia mereka sendiri. Meskipun keluarga sempurna gambar ini dibangun di atas penipuan, para Pemalsu secara bertahap memahami bahwa cinta yang mereka bagi satu sama lain mengalahkan segalanya.', 'https://cdn.myanimelist.net/images/anime/1441/122795.webp', NULL, NULL),
	(22, 'Summertime Render', 8.55, 'OLM', 'Spring', '2022', 'Mystery, Supranatural, Suspense', 'Sejak kematian orang tuanya, Shinpei Ajiro tinggal bersama keluarga Kofune dan kedua putri mereka—Mio dan Ushio. Meskipun ia kemudian meninggalkan pulau asalnya untuk melanjutkan pendidikannya di Tokyo, Shinpei kembali setelah Ushio secara tragis tenggelam saat berusaha menyelamatkan seorang gadis kecil. Selama pemakaman, sahabatnya memberi tahu dia tentang memar yang ditemukan di sekitar leher Ushio, menimbulkan keraguan atas penyebab kematiannya.Mencurigai telah terjadi pembunuhan, Shinpei mengevaluasi kembali peristiwa baru-baru ini, tetapi insiden aneh terus terjadi. Orang-orang yang hilang dan kejadian lain yang tidak dapat dijelaskan membuat Mio mengingat cerita rakyat lama yang merujuk pada entitas yang disebut "Bayangan", yang mungkin tidak sepenuhnya fantasi. Seharusnya, pertemuan dengan Bayangan seseorang menubuatkan kematian yang akan datang dari orang tersebut.Menghadapi sisi gelap Pulau Hitogashima, Shinpei menentang takdirnya yang suram untuk memenuhi keinginan terakhir Ushio—untuk melindungi Mio.', 'https://cdn.myanimelist.net/images/anime/1120/120796.webp', NULL, NULL),
	(23, 'Ao Ashi', 8.29, 'Production I.G', 'Spring', '2022', 'Sports', 'Di kota pedesaan yang tenang, sorotan tim sepak bola sekolah menengah pertama terletak pada satu pemain: Ashito Aoi. Dikenal karena gerakannya yang tidak dapat diprediksi dan gaya bermain yang mementingkan diri sendiri, Ashito adalah satu-satunya pembangkit tenaga yang mendorong timnya melalui turnamen penyisihan sekolah menengah yang penting. Namun, kemenangan beruntun mereka berumur pendek — lawan menyebabkan Ashito kehilangan kesabaran dan bertindak kasar, mengakibatkan dia dikeluarkan dari sisa permainan.Tanpa pemain bintang mereka, tim tersebut dengan cepat tersingkir dari turnamen. Saat dia yakin semua harapan telah hilang, Ashito didekati oleh pelatih tim yunior bernama Tatsuya Fukuda yang merasakan potensi dalam dirinya, dan Fukuda mengundangnya untuk uji coba di Tokyo. Dalam suasana asing yang dikelilingi oleh bakat, Ashito harus mengeluarkan kemampuan terbaiknya untuk membuktikan dirinya dan mengamankan apa yang bisa menjadi karier yang mengubah hidup.', 'https://cdn.myanimelist.net/images/anime/1731/120871.webp', NULL, NULL),
	(24, 'Paripi Kuomei', 8.22, 'P.A. Works', 'Spring', '2022', 'Comedy', 'Zhuge Kongming mendapatkan reputasi sebagai salah satu ahli taktik terhebat dari periode Tiga Kerajaan Tiongkok abad ketiga. Setelah memimpin pasukannya melalui kemenangan yang melelahkan yang tak terhitung jumlahnya, Kongming jatuh sakit parah selama Pertempuran Dataran Wuzhang. Kelelahan dan penyesalan yang berasal dari perang yang tampaknya tidak pernah berakhir mengejarnya, dan saat dia menarik napas terakhirnya, Kongming berharap jika dia bereinkarnasi, dia akan terlahir kembali di era yang lebih damai.Keinginannya terkabul, dan Kongming terbangun di Tokyo modern dengan tubuh yang lebih muda dan ingatannya utuh. Terdorong ke dunia asing, dia menemukan jalannya ke klub malam dan bertemu Eiko Tsukimi, seorang calon penyanyi yang penampilannya langsung memikatnya. Mengasihani kebingungannya, Eiko membawa Kongming di bawah sayapnya dan mengajarinya tentang dunia saat ini, yang membuat Kongming tertarik pada musik kontemporer. Melihat potensi musik Eiko yang luar biasa, Kongming bersumpah untuk membuat dunia mengenalinya dan segera mengambil peran sebagai manajernya.Tidak mengherankan, industri musik tidak memaafkan mereka yang membuat kesalahan sekecil apa pun. Tetap saja, Kongming bertekad untuk mencapai tujuannya — bahkan jika dia harus menggunakan strategi perang yang terkenal dia gunakan di kehidupan sebelumnya!', 'https://cdn.myanimelist.net/images/anime/1970/122297.webp', NULL, NULL),
	(25, 'Komi-san wa, comyushou desu. 2nd Season', 8.12, 'OLM', 'Spring', '2022', 'Comedy', 'Setelah festival budaya yang menarik dan penting, Shouko Komi melanjutkan usahanya untuk mendapatkan seratus teman bersama teman dan teman sekelasnya Hitohito Tadano. Saat musim dingin dimulai, kelas tersebut diikuti oleh siswa nakal Makoto Katai, yang telah absen sejak minggu pertama sekolah. Meski penampilannya mengintimidasi, Katai kesulitan berkomunikasi dengan orang lain dan hanya ingin berteman dengan teman sekelasnya.Saat pertemanan baru terbentuk dan pertemanan saat ini semakin dalam, hubungan Komi dan Tadano mulai berubah—meskipun tidak selalu menjadi lebih buruk.', 'https://cdn.myanimelist.net/images/anime/1108/121157.webp', NULL, NULL),
	(26, 'Date A Live IV', 7.81, 'GEEK TOYS', 'Spring', '2022', 'Comedy, Romance, Sci-Fi', 'Terlepas dari banyak tantangan yang telah dia atasi sejauh ini, misi Shidou Itsuka dengan Ratatoskr masih jauh dari selesai. Beranjak dari rutinitas hariannya, Shidou bertemu dengan seorang wanita kelaparan yang terbaring di jalan dan akhirnya membantunya. Setelah keduanya tiba di apartemennya, wanita itu memperkenalkan dirinya sebagai Nia Honjou — seorang seniman manga populer yang bekerja dengan nama pena. Namun, langsung ke pengejaran, Nia mengungkapkan bahwa dia juga Roh dan mengetahui operasi rahasia Shidou.Tertarik untuk melihat karismanya secara langsung, Nia menantang Shidou untuk memenangkan hatinya dalam sebuah kencan. Saat dia mencari kesempatan untuk menyegel kekuatannya, Shidou belajar lebih banyak tentang Nia dan sejarahnya dengan Deus Ex Machina Industries, nama yang sangat dia kenal...', 'https://cdn.myanimelist.net/images/anime/1368/121281.webp', NULL, NULL),
	(27, 'Love Live! Nijigasaki Gakuen School Idol Doukoukai', 7.72, 'Sunrise', 'Spring', '2022', 'Slice of Life', 'Klub Idol Sekolah Menengah Nijigasaki terus mendapatkan popularitas seiring dengan pertumbuhan reputasinya, bahkan menarik perhatian calon idola sekolah Zhong Lanzhu. Namun, ketika Lanzhu mengunjungi klub dan berinteraksi dengan anggotanya, dia menyadari bahwa cita-cita mereka berbeda dengan dirinya. Ini memicu awal persaingan antara Lanzhu dan anggota klub, saat dia menantang mereka untuk melihat siapa yang dapat memikat lebih banyak penonton di School Idol Festival mendatang.Dengan demikian, klub idola sekolah memulai babak baru dalam pencariannya untuk mencapai bintang idola. Menjadi lebih bersatu dari sebelumnya, gadis-gadis itu terus berlatih untuk festival — ingin menunjukkan kepada Lanzhu apa artinya menjadi idola sekolah.', 'https://cdn.myanimelist.net/images/anime/1586/121947.webp', NULL, NULL),
	(28, 'Kimetsu no Yaiba: Yuukaku-hen', 8.83, 'Ufotable', 'Winter', '2022', 'Action, Fantasy', 'Kehancuran insiden Kereta Mugen masih membebani anggota Korps Pembunuh Iblis. Meskipun diberi waktu untuk pulih, hidup harus terus berjalan, karena orang jahat tidak pernah tidur: setan ganas sedang meneror para wanita memikat di Distrik Hiburan Yoshiwara. Pilar Suara, Tengen Uzui, dan ketiga istrinya ada dalam kasus ini. Namun, ketika dia segera kehilangan kontak dengan pasangannya, Tengen takut akan yang terburuk dan meminta bantuan Tanjirou Kamado, Zenitsu Agatsuma, dan Inosuke Hashibira untuk menyusup ke rumah-rumah paling menonjol di distrik itu dan menemukan iblis Tingkat Atas yang bejat.', 'https://cdn.myanimelist.net/images/anime/1908/120036.webp', NULL, NULL),
	(29, 'Shingeki no Kyojin: The Final Season Part 2', 8.78, 'MAPPA', 'Winter', '2022', 'Action, Drama', 'Melawan mantan sekutu dan musuhnya, Eren Yeager menjalankan rencana bencana. Di bawah bimbingan Titan Binatang, Zeke, Eren mengambil tindakan ekstrem untuk mengakhiri konflik kuno antara Marley dan Eldia—tetapi niat sebenarnya tetap menjadi misteri. Menggali jauh ke dalam masa lalu keluarganya, Eren berjuang untuk mengendalikan takdirnya sendiri.Sementara itu, negara Marley dan Eldia yang telah lama berseteru memanfaatkan tentara dan Titan dalam perlombaan brutal untuk melenyapkan yang lain. Reiner Braun menggunakan kekuatannya sendiri dalam upaya putus asa untuk menahan kekuatan militer Eren sendiri, dan sesama Tetua—anak-anak Falco Grice dan Gabi Braun—berjuang untuk bertahan hidup dalam kekacauan yang sedang berlangsung.Di tempat lain, teman masa kecil Eren Mikasa Ackerman dan Armin Arlert tetap dipenjara bersama mantan rekan Survey Corps Eren, semuanya terganggu oleh transformasi mengerikan Eren. Di bawah kepercayaan buta bahwa Eren diam-diam masih menyimpan niat baik, Mikasa dan yang lainnya terlibat dalam upaya untuk menyelamatkan jiwa teman mereka.', 'https://cdn.myanimelist.net/images/anime/1948/120625.webp', NULL, NULL),
	(30, 'Karakai Jouzu no Takagi-san 3', 8.46, 'Shin-Ei Animation', 'Winter', '2022', 'Comedy', 'Saat liburan musim panas akan segera berakhir, Nishikata bersemangat untuk mencoba keisengan terbarunya dan akhirnya mengalahkan teman sekelasnya, Takagi, untuk selamanya. Terlepas dari kekalahan beruntunnya, dia perlahan-lahan mulai mengetahui cara kerja pikiran liciknya yang tak henti-hentinya. Namun, dia segera menyadari bahwa motivasi Takagi di balik godaannya mungkin bukan seperti yang dia duga sebelumnya. Namun, satu hal yang pasti: setiap hari yang menyenangkan untuk menyusun strategi dan bersaing membuat keduanya lebih dekat dari sebelumnya.', 'https://cdn.myanimelist.net/images/anime/1861/120361.webp', NULL, NULL),
	(31, 'Sono Bisque Doll wa Koi wo Suru', 8.29, 'Cloverworks', 'Winter', '2022', 'Romance, Slife of Life', 'Siswa sekolah menengah Wakana Gojou menghabiskan hari-harinya menyempurnakan seni membuat boneka hina, berharap pada akhirnya mencapai tingkat keahlian kakeknya. Sementara teman-teman remajanya menyibukkan diri dengan budaya pop, Gojou menemukan kebahagiaan dalam menjahit pakaian untuk bonekanya. Meskipun demikian, dia berusaha keras untuk merahasiakan hobi uniknya, karena dia percaya bahwa dia akan diejek jika hal itu terungkap.Masukkan Marin Kitagawa, seorang gadis yang luar biasa cantik yang kepercayaan diri dan ketenangannya sangat kontras dengan kelembutan Gojou. Akan bertentangan dengan akal sehat jika Gojou yang tidak punya teman bergaul dengan orang-orang seperti Kitagawa, yang selalu dikelilingi oleh teman-temannya. Namun, hal yang tak terbayangkan terjadi ketika Kitagawa menemukan kehebatan Gojou dengan mesin jahit dan dengan ceria mengakui kepadanya tentang hobinya sendiri: cosplay. Karena keterampilan menjahitnya sangat menyedihkan, dia memutuskan untuk meminta bantuannya.Saat Gojou dan Kitagawa bekerja sama dalam satu demi satu pakaian cosplay, mereka tidak bisa tidak menjadi dekat — meskipun hidup mereka terpisah jauh.', 'https://cdn.myanimelist.net/images/anime/1179/119897.webp', NULL, NULL),
	(32, 'Vanitas no Karte Part 2', 8.21, 'Bones', 'Winter', '2022', 'Supranatural', 'Vanitas dan Noé Archiviste pergi ke kota Gévaudan untuk mencari "Binatang", makhluk besar mirip serigala yang telah membantai ratusan orang. Menduga bahwa Beast adalah vampir pembawa kutukan, Vanitas terutama bertujuan untuk menyembuhkannya menggunakan kekuatan grimoire-nya.Sepanjang jalan, keduanya terpisah dan tiba-tiba melakukan perjalanan kembali ke masa lalu — ke saat yang tepat ketika Beast bersembunyi di hutan. Setelah pertempuran melawan serigala raksasa dan pemburu vampir, Vanitas memutuskan untuk bekerja sama dengan Jeanne untuk menemukan Noé. Meskipun menjadi sekutu, tujuan Jeanne adalah kebalikan dari tujuan Vanitas, karena dia ditugaskan untuk membunuh Beast — curiga itu mungkin seseorang yang pernah dia kenal.Sementara itu, Noé yang terluka parah dijemput oleh Chloé d\'Apchier yang misterius dan pelayannya. Seperti Noé, Chloé adalah vampir yang keberadaannya terhapus dari pengetahuan publik. Dia telah menjadi wali bagi generasi mendatang dan pernah mencoba menemukan cara untuk menjadi manusia kembali. Sementara Noé berterima kasih kepada Chloé atas keramahtamahannya, sedikit yang dia tahu bahwa dia mungkin berpihak pada kekuatan yang jauh lebih berbahaya daripada Binatang itu sendiri.', 'https://cdn.myanimelist.net/images/anime/1247/120579.webp', NULL, NULL),
	(33, 'Princess Connect! Re:Dive Season 2', 7.84, 'CygamesPictures', 'Winter', '2022', 'Adventure, Comedy, Fantasy, Gourmet', 'Anggota Gourmet Guild—Yuuki, Kokkoro, Pecorine, dan Karyl—terus menjelajahi dunia untuk mengejar tujuan mereka mencari semua makanan lezat yang ada. Namun, saat petualangan mereka berlanjut, misteri di balik ingatan Yuuki, kesetiaan Karyl, dan warisan Pecorine mulai bersatu—tampaknya membentuk kebenaran yang membentuk fondasi dunia.', 'https://cdn.myanimelist.net/images/anime/1906/117145.webp', NULL, NULL),
	(34, 'Genjitsu Shugi Yuusah no Oukoku Saikenki Part 2', 7.45, 'J.C.Staff', 'Winter', '2022', 'Action, Fantasy, Romance', 'Bersama dengan para pembantunya yang berbakat, "Pahlawan Realis" Kazuya Souma melanjutkan pencariannya untuk menghidupkan kembali Kerajaan Elfrieden melalui reformasi administrasi. Setelah berhasil menaklukkan Van—ibukota Kerajaan Amidonia—Kazuya kini menghadapi utusan dari Kekaisaran Gran Chaos, yang ingin menjatuhkan hukuman karena melanggar larangan perang yang ditetapkan oleh Perjanjian Deklarasi Umat Manusia. Terlepas dari situasi yang mengerikan, Kazuya melihat jalan untuk menghindari konflik yang tidak perlu sambil mendapatkan sekutu baru. Dengan rencananya yang tampaknya sempurna, satu-satunya penghalang untuk sukses adalah mendapatkan persetujuan dari utusan tersebut.', 'https://cdn.myanimelist.net/images/anime/1088/120068.webp', NULL, NULL),
	(35, 'Tensai Ouji no Akaji Kokka Saisei Jutsu', 7.4, 'Yokohama Animation Lab', 'Winter', '2022', 'Comedy, Fantasy', 'Raja Natra jatuh sakit, meninggalkan satu-satunya harapan kerajaannya kepada putranya, Pangeran Wein Salema Arbalest. Dikenal cakap dan bijaksana, dia adalah kandidat yang sempurna untuk menjadi bupati pangeran. Namun, jika sang pangeran ingin mengatakan sesuatu tentang masalah ini, dia lebih suka menjual Kerajaan Natra kepada penawar tertinggi! Karena dia memegang otoritas takhta, tidak ada yang bisa menghentikan Wein melelang negara dan menggunakan keuntungannya untuk pensiun dengan nyaman. Yang perlu dia lakukan hanyalah menaikkan nilai kerajaan kecil untuk memaksimalkan keuntungannya. Tetapi apakah rencana besar Wein akan berhasil masih harus dilihat, karena kecerdasannya bahkan sering melampaui harapannya sendiri — sangat menguntungkan warga Natra yang tidak sadar.', 'https://cdn.myanimelist.net/images/anime/1263/119511.webp', NULL, NULL),
	(36, 'Heike Monogatari', 7.76, 'Science SARU', 'Winter', '2022', 'Drama', 'Klan Taira, juga dikenal sebagai Heike, memegang otoritas besar atas Jepang. Ketika seorang gadis muda, berbakat dengan mata aneh yang memungkinkannya melihat masa depan, dengan bodohnya tidak menghormati klan, ayahnya membayar harga kejahatannya dengan nyawanya. Segera setelah itu, seperti sudah ditakdirkan, Taira no Shigemori — putra tertua pemimpin klan — menemukan gadis malang yang sama, yang sekarang menyebut dirinya "Biwa". Biwa memberitahunya bahwa kejatuhan Heike sudah dekat. Setelah mengetahui ketidakadilan besar yang diderita Biwa di tangan Heike, Shigemori bersumpah untuk menerima dan merawatnya daripada membiarkannya dibunuh. Di era ketegangan militer yang meningkat, Heike berada di tengah perebutan kekuasaan yang licik, dan perang berlumuran darah akan segera terjadi. Shigemori, yang matanya memungkinkan dia untuk melihat roh orang mati, cemas sekaligus berharap untuk mencegah kematian klannya. Biwa, bagaimanapun, enggan mengungkapkan masa depan kepadanya dan harus beradaptasi dengan kehidupan barunya yang penuh dengan kebahagiaan dan kesedihan dalam babak penting dalam sejarah Jepang ini.', 'https://cdn.myanimelist.net/images/anime/1282/119979.webp', NULL, NULL);
/*!40000 ALTER TABLE `titles` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
